spring.application.name=SpringCore_Module_3.3
spring.profiles.active=local


certificate.path=keystore.jks
certificate.alias=${CERTIFICATE_ALIAS}
certificate.password=${CERTIFICATE_PASSWORD}

jwt.expiration-ms=3600000